### ISSUE TITLE
GIS版本升级需要客户端自行清理缓存，GIS需要解决此问题，自动进行更新

### ISSUE THREAD

**Issue by ketty0914** [duscin/yumgis2#101]

**Comment by FuZhenn** [comment]
参考 @wsw0108 所发文章里的技术路线
https://www.zhihu.com/question/27548038/answer/37140329

更新目前yumgis前端开发的技术工具，用新的css和js持续集成了流程代替现有的人工方式以解决浏览器缓存的问题

参与的人员有：邹红，付镇，王俊及其他涉及yumgis开发的同事
