### ISSUE TITLE
自定义label与table截图问题

### ISSUE THREAD

**Issue by brucin** [duscin/yumgis2#104]
1、label应该是由于box宽度自适应的缘故，导致截图的中的box为很细的一条线，文字不显示；
2、table在截图中表格的形状正确的，但是文字过大。

![1455591206754](https://cloud.githubusercontent.com/assets/11517403/13065923/62f18e60-d49c-11e5-9f7d-772cd848776e.png)

**Comment by FuZhenn** [comment]
更新layertalks后, 该问题应已解决
