### ISSUE TITLE
【专题图】做图时隐藏了不要的聚客点,但是在动画预览的时候又显示出来了;

### ISSUE THREAD

**Issue by raocheng** [duscin/yumgis2#130]
![009](https://cloud.githubusercontent.com/assets/16470436/14515303/4e5e665a-022b-11e6-98a5-d386cb908008.png)

**Comment by brucin** [comment]
已修复，请测试。

**Comment by raocheng** [comment]
这个是关于图层里面的隐藏,不是节点数据树的隐藏;

**Comment by brucin** [comment]
同#144
