### ISSUE TITLE
轨道线图层修改渲染效果后，在数据列表中定位图形时报错

### ISSUE THREAD

**Issue by zouhong66** [duscin/yumgis2#21]
Uncaught TypeError: Cannot read property 'show' of undefined

**Comment by zouhong66** [comment]
openInfoWindow:function(coordinate) {
        this._infoWindow.show(coordinate);
        return this;
    },

第一行报错

**Comment by zouhong66** [comment]
现在是不报错误，定位渲染后的线图层，不会弹出tip框

**Comment by zouhong66** [comment]
面图层同样问题

**Comment by FuZhenn** [comment]
该问题不是引擎引起, 而是layer_query.js 1079行中的geometry已经不在图层上, 无法打开信息框导致的.

该问题应该是取消渲染时, 删掉的是图形本体, 而不是渲染的图形导致

**Comment by zouhong66** [comment]
ok
