### ISSUE TITLE
mapObj.identify方法检索不到空间数据

### ISSUE THREAD

**Issue by zouhong66** [duscin/yumgis2#35]

**Comment by FuZhenn** [comment]
identify查不到数据的问题已经解决.

但因为layer_query.js第449行,王俊的代码中对空间库查询到的geometry都注册了右键菜单, 而geometry上的右键菜单优先级高于map的右键菜单, 所以map的右键菜单被屏蔽了.

@brucin 也一起来帮忙看看这个问题

**Comment by zouhong66** [comment]
昨天我将上面的代码注释后还是看不到。奇怪了，今天早上来就能看到，难道是缓存的影响？

**Comment by zouhong66** [comment]
我昨天还debug进去，发现返回确实没有结果。

**Comment by FuZhenn** [comment]
是我昨天修改更新过了

**Comment by zouhong66** [comment]
明白，问题解决。
