### ISSUE TITLE
【专题图】填充色、边框色、字体色；

### ISSUE THREAD

**Issue by raocheng** [duscin/yumgis2#61]
1、图标能否跟office一样风格；
2、变色会动态，图标没有用好；
3、线框图标可以用毛笔；
![1](https://cloud.githubusercontent.com/assets/16470436/12162551/ca8e3c58-b53e-11e5-9369-10c687a1e8c1.jpg)

**Comment by brucin** [comment]
已经统一为图层渲染一样的颜色选择面板。
