### ISSUE TITLE
【专题图】动态表格；

### ISSUE THREAD

**Issue by raocheng** [duscin/yumgis2#72]
1、IE9没有选择图层数据；
![7](https://cloud.githubusercontent.com/assets/16470436/12163381/17afd060-b548-11e5-8819-b66959c705b3.jpg)
2、删除数据后，编号没有删除，没有联动；
![8](https://cloud.githubusercontent.com/assets/16470436/12163518/3ee760f2-b549-11e5-83f0-6f8ee0c64cad.jpg)
3、要有刷新按钮；
4、表格移动与不移动时按钮的颜色是不是要有变化，有点看不清楚；
![9](https://cloud.githubusercontent.com/assets/16470436/12163574/c1fb5890-b549-11e5-9929-37948508a3f6.png)
5、删除整个表格过程太复杂要优化；
![10](https://cloud.githubusercontent.com/assets/16470436/12163600/0fd72ce2-b54a-11e5-9c7c-46b6c8fcb653.jpg)
![12](https://cloud.githubusercontent.com/assets/16470436/12163601/10196bf2-b54a-11e5-94d4-1d93b2a379b4.jpg)
6、点表格里面的某一行数据是不是标注的图标要有变化表示选中的状态；
![13](https://cloud.githubusercontent.com/assets/16470436/12163729/f6d317c8-b54a-11e5-88ee-ec503ef0d890.png)

**Comment by FuZhenn** [comment]
嗨, 提一个建议, 一个issue里一次性提很多个bug管理起来不方便, 需要对issue中每个问题都分别跟踪, 只要有一个bug没解决, issue的状态始终是开放的

所以最好一个issue只提一个bug, 这样方便管理一些

**Comment by raocheng** [comment]
ok;
