### ISSUE TITLE
加载动态图层（PNG图标）后缩放地图出现位置偏差很大

### ISSUE THREAD

**Issue by wsw0108** [duscin/yumgis2#77]

**Comment by wsw0108** [comment]
@zouhong66 是用的百度底图还是什么？

**Comment by zouhong66** [comment]
百度底图

**Comment by wsw0108** [comment]
动态图层的options增加了两个选项
- inputCRS
- resultCRS

使用百度底图的话，例子如下
```
var options = {
    baseUrl: 'http://127.0.0.1:8080/maps',
    mapdb: 'testdb',
    // need to set resultCRS as below
    resultCRS: maptalks.CRS.createProj4('+proj=bmerc +datum=BD09'),
    layers: [layerDef]
};
var layer = new maptalks.DynamicLayer('id', options);
```
https://github.com/MapTalks/maptalks.js/blob/change-crs-for-query/examples/layer/dynamic-baidu.html#L65

当前支持的proj4的写法，可以看[这里](https://github.com/wsw0108/proj4m#supported-projection)
