### ISSUE TITLE
8.T-SQL serverlet中用到的 EngineService中坐标转换以及图形求交运算 没有对应的接口

### ISSUE THREAD

**Issue by zouhong66** [duscin/yumgis2#8]
1.List<Coordinate> coords = service.convertCoordinate(Arrays.asList(rings), CoordinateType.gcj02, CoordinateType.bd09ll);
2.List<Geometry> intersections = filterGeo.interection(geosNeedScale.toArray(scaleGeos), mapControl);

**Comment by zouhong66** [comment]
3.mapControl.computeArea(new Geometry[]{geo})[0];

**Comment by zouhong66** [comment]
第一个坐标转换 ok

**Comment by FuZhenn** [comment]
相交接口:
Geometry[] inters = new TopoQuery(host,port).intersection(src, targets);

面积计算接口:
Measurer.computeArea(geometry,null);

**Comment by zouhong66** [comment]
ok
